import { FormEvent, useState } from 'react';
import type { WeddingSide } from '../config/wedding';
import { submitRsvp, submitWish } from '../services/submissions';

export function Response({ guest, side }: { guest: string; side: WeddingSide }) {
 const [mode,setMode]=useState<'rsvp'|'wish'>('rsvp'); const [state,setState]=useState(''); const unavailable='Dịch vụ xác nhận sẽ sớm được mở. Vui lòng liên hệ trực tiếp với cô dâu hoặc chú rể.';
 async function send(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const data=new FormData(e.currentTarget); const r=mode==='rsvp' ? await submitRsvp({guestName:String(data.get('name')||''),side,attendance:String(data.get('attendance')),partySize:Number(data.get('partySize')||1),message:String(data.get('message')||'')}) : await submitWish({name:String(data.get('name')||''),side,message:String(data.get('message')||'')}); setState(r.ok ? 'Đã gửi. Cảm ơn bạn!' : r.reason === 'unavailable' ? unavailable : 'Có lỗi nhỏ, vui lòng thử lại sau.'); }
 return <section className="scene response-scene" id="response"><div className="response-copy"><p className="eyebrow">CHUNG VUI CÙNG CHÚNG MÌNH</p><h2>{mode==='rsvp'?'Xác nhận tham dự':'Gửi lời chúc'}</h2><p>Chúng mình rất mong được đón bạn trong ngày vui này.</p></div><div className="response-work"><div className="response-actions"><button className={mode==='rsvp'?'active':''} onClick={()=>{setMode('rsvp');setState('')}}>XÁC NHẬN THAM DỰ</button><button className={mode==='wish'?'active':''} onClick={()=>{setMode('wish');setState('')}}>GỬI LỜI CHÚC</button></div><form onSubmit={send}><label>Họ và tên<input required name="name" maxLength={72} defaultValue={guest} placeholder="Tên của bạn"/></label>{mode==='rsvp' && <><label>Bạn sẽ tham dự?<select name="attendance" defaultValue="Có, tôi sẽ tham dự"><option>Có, tôi sẽ tham dự</option><option>Rất tiếc, tôi không thể tham dự</option></select></label><label>Số người<select name="partySize" defaultValue="1"><option value="1">01 người</option><option value="2">02 người</option><option value="3">03 người</option><option value="4">04 người</option></select></label></>}<label>{mode==='rsvp'?'Lời nhắn (không bắt buộc)':'Lời chúc của bạn'}<textarea required={mode==='wish'} name="message" maxLength={360} rows={3} placeholder={mode==='wish'?'Viết lời chúc của bạn':'Gửi chúng mình một lời nhắn'}/></label><button className="submit" type="submit">{mode==='rsvp'?'GỬI XÁC NHẬN':'GỬI LỜI CHÚC'} <span>→</span></button>{state && <p className="form-state" role="status">{state}</p>}</form></div></section>
}
