import { useEffect, useRef, useState } from 'react';
import { cinematicImage, finaleImage, heroImage, introImage, wedding, type WeddingSide } from './config/wedding';
import { guestFromSearch } from './utils/guest';
import { Gallery } from './components/Gallery';
import { Response } from './components/Response';
import { Gift } from './components/Gift';

function Music({ opened }: { opened: boolean }) { const audio=useRef<HTMLAudioElement>(null); const [playing,setPlaying]=useState(false); useEffect(()=>{if(opened&&wedding.music.src) audio.current?.play().then(()=>setPlaying(true)).catch(()=>{});},[opened]); const toggle=()=>{if(!wedding.music.src)return;if(playing){audio.current?.pause();setPlaying(false)}else audio.current?.play().then(()=>setPlaying(true)).catch(()=>{})};return <><audio ref={audio} preload="none" src={wedding.music.src}/><button className={`music ${playing?'playing':''}`} onClick={toggle} aria-label={playing?'Tạm dừng nhạc':'Bật nhạc'}><i/><i/><i/><span>{playing?'TẮT NHẠC':'NHẠC'}</span></button></> }
function Ceremony({ side }: {side: WeddingSide}) { const entries=side==='both'?(['groom','bride'] as const):[side]; return <section data-testid="ceremony" className={`scene ceremony-scene ${entries.length===1?'one-event':''}`}><div className="date-lockup"><span>19</span><i>10</i><span>2026</span></div><div className="ceremonies">{entries.map(key=>{const item=wedding.locations[key];return <article key={key}><p className="eyebrow">{item.label}</p><h2>{item.time}</h2><p>{item.address}</p><a href={item.map} target="_blank" rel="noreferrer">Chỉ đường <span>→</span></a></article>})}</div></section> }
export function App(){const [{guest,side}]=useState(guestFromSearch);const [opened,setOpened]=useState(false);useEffect(()=>{document.title=wedding.seo.title;},[]);const invitee=guest?`Trân trọng kính mời ${guest}`:wedding.copy.intro;return <main className={opened?'opened':''}><Music opened={opened}/><section className="scene cover-scene" aria-label="Thiệp cưới Tuấn Hùng và Sao Mai"><img className="cover-photo" src={heroImage} srcSet={`${heroImage}&w=768 768w, ${heroImage}&w=1200 1200w, ${heroImage}&w=1600 1600w`} sizes="100vw" fetchPriority="high" alt="Khoảnh khắc của Tuấn Hùng và Sao Mai"/><div className="cover-shade"/><div className="cover-content"><p>{invitee}</p><h1><span>Tuấn Hùng</span><em>&</em><span>Sao Mai</span></h1><div className="cover-date"><span>{wedding.date}</span><small>{wedding.lunarDate}</small></div><button className="open-invitation" onClick={()=>setOpened(true)} aria-label="Mở thiệp cưới"><i>囍</i>MỞ THIỆP</button></div>{!opened&&<div className="curtain left"/>}{!opened&&<div className="curtain right"/>}</section>
<section className="scene intro-scene"><div className="intro-photo"><img src={introImage} loading="lazy" alt="Cô dâu và chú rể trong bộ ảnh cưới"/></div><div className="intro-words"><p className="eyebrow">19 · 10 · 2026</p><h2>Ngày chúng mình<br/>về chung một nhà.</h2><p>Niềm vui sẽ trọn vẹn hơn khi có sự hiện diện của bạn.</p></div></section>
<Ceremony side={side}/><section className="scene cinematic-scene"><img src={cinematicImage} loading="lazy" alt="Khoảnh khắc lãng mạn của cặp đôi"/><p>{wedding.copy.cinematic}</p></section><Gallery/><Response guest={guest} side={side}/><Gift side={side}/><section className="scene finale-scene"><img src={finaleImage} loading="lazy" alt="Tuấn Hùng và Sao Mai"/><div><p>{wedding.copy.finale}</p><span>{wedding.date}</span></div></section></main>}
